/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class TelaConfiguracao extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form Panel
     */
    public TelaConfiguracao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLinhas = new javax.swing.JLabel();
        nroColunas = new javax.swing.JSpinner();
        jLabelRefugiados = new javax.swing.JLabel();
        nroRefugiados = new javax.swing.JSpinner();
        botaoIniciar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nroLinhas = new javax.swing.JSpinner();
        jLabelColunas = new javax.swing.JLabel();
        jLabelBombeiros = new javax.swing.JLabel();
        nroBombeiros = new javax.swing.JSpinner();
        jLabelFogos = new javax.swing.JLabel();
        jLabelAmbulancias = new javax.swing.JLabel();
        nroFogos = new javax.swing.JSpinner();
        nroAmbulancias = new javax.swing.JSpinner();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Simulação combate ao fogo e resgate de vítimas");

        jLabelLinhas.setText("Nº Linhas");

        nroColunas.setModel(new javax.swing.SpinnerNumberModel(15, 10, 20, 1));

        jLabelRefugiados.setText("Nº de Refugiados");

        nroRefugiados.setModel(new javax.swing.SpinnerNumberModel(5, 1, 10, 1));

        botaoIniciar.setText("Iniciar Simulação");
        botaoIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoIniciarMouseClicked(evt);
            }
        });
        botaoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarActionPerformed(evt);
            }
        });
        botaoIniciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoIniciarKeyPressed(evt);
            }
        });

        jLabel4.setText("Autores: Bruno Emer e Marcos Grzeça");

        nroLinhas.setModel(new javax.swing.SpinnerNumberModel(15, 10, 20, 1));

        jLabelColunas.setText("Nº Colunas");

        jLabelBombeiros.setText("Nº de Bombeiros");

        nroBombeiros.setModel(new javax.swing.SpinnerNumberModel(5, 1, 10, 1));

        jLabelFogos.setText("Nº de Fogos");

        jLabelAmbulancias.setText("Nº de Ambulâncias");

        nroFogos.setModel(new javax.swing.SpinnerNumberModel(5, 1, 10, 1));

        nroAmbulancias.setModel(new javax.swing.SpinnerNumberModel(5, 1, 10, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(botaoIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRefugiados)
                    .addComponent(jLabelLinhas)
                    .addComponent(nroLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nroRefugiados, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nroFogos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFogos))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabelBombeiros))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nroColunas)
                            .addComponent(jLabelColunas)
                            .addComponent(nroBombeiros, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(nroAmbulancias, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelAmbulancias)))
                .addGap(695, 695, 695))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLinhas)
                    .addComponent(jLabelColunas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nroLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nroColunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRefugiados)
                    .addComponent(jLabelBombeiros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nroRefugiados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nroBombeiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFogos)
                    .addComponent(jLabelAmbulancias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nroFogos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nroAmbulancias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void botaoIniciarKeyPressed(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:
        System.out.println("CLIQUEI");

    }                                       

    private void botaoIniciarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void botaoIniciarMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    	int varNroLinhas = (int) nroLinhas.getValue();
        int varNroColunas = (int) nroColunas.getValue();
        int varNroRefugiados = (int) nroRefugiados.getValue();
        int varNroBombeiros = (int) nroBombeiros.getValue();
        int varNroFogos = (int) nroFogos.getValue();
        int varNroAmbulancias = (int) nroAmbulancias.getValue();
        
        if ((varNroAmbulancias + varNroBombeiros + varNroFogos + varNroRefugiados) > (varNroLinhas * varNroColunas - 10)) {
            TelaConfiguracao tela = null;
            JOptionPane.showMessageDialog(tela, "O número total de objetos selecionado não pode ser maior que o espaço do ambiente - 10 posições.");
        } else {
        	Main.iniciarSimulacao(varNroLinhas, varNroColunas, varNroRefugiados, varNroBombeiros, varNroFogos, varNroAmbulancias);
        }
    }                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConfiguracao().setVisible(true);
            }
        });
    }
    

   /* public void setFdText(String teste) {
        fdField.setText(teste);
    }
    
    public void setPdText(String teste) {
        pdField.setText(teste);
    }
    
    public void setPpText(String texto) {
        ppField.setText(texto);
    }
    
    public void setE500Text(String teste) {
        e5000Field.setText(teste);
    }
    
    public void setE12000Text(String texto) {
        e12000Field.setText(texto);
    }
    
    public void setE18000Text(String texto) {
        e18000Field.setText(texto);
    }
    
    public void setE20000Text(String texto) {
        e20000Field.setText(texto);
    }
    
    public void setE15000Text(String texto) {
        e15000Field.setText(texto);
    }
    
    public void setE10000Text(String texto) {
        e10000.setText(texto);
    }*/
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton botaoIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAmbulancias;
    private javax.swing.JLabel jLabelBombeiros;
    private javax.swing.JLabel jLabelColunas;
    private javax.swing.JLabel jLabelFogos;
    private javax.swing.JLabel jLabelLinhas;
    private javax.swing.JLabel jLabelRefugiados;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JSpinner nroAmbulancias;
    public javax.swing.JSpinner nroBombeiros;
    public javax.swing.JSpinner nroColunas;
    public javax.swing.JSpinner nroFogos;
    public javax.swing.JSpinner nroLinhas;
    public javax.swing.JSpinner nroRefugiados;
    // End of variables declaration                   
}
